set (JANCY_VERSION_MAJOR     1)
set (JANCY_VERSION_MINOR     7)
set (JANCY_VERSION_REVISION  0)
set (JANCY_VERSION_TAG)

set (JANCY_VERSION_FILE_SUFFIX "${JANCY_VERSION_MAJOR}.${JANCY_VERSION_MINOR}.${JANCY_VERSION_REVISION}")

if (NOT "${JANCY_VERSION_TAG}" STREQUAL "")
	set (JANCY_VERSION_TAG_SUFFIX " ${JANCY_VERSION_TAG}")
	set (JANCY_VERSION_FILE_SUFFIX "${JANCY_VERSION_FILE_SUFFIX}-${JANCY_VERSION_TAG}")
else ()
	set (JANCY_VERSION_TAG_SUFFIX)
endif ()

set (JANCY_VERSION_COMPANY   "Tibbo Technology Inc")
set (JANCY_VERSION_YEARS     "2007-2015")
