set (VERSION_MAJOR     1)
set (VERSION_MINOR     5)
set (VERSION_REVISION  7)
set (VERSION_TAG)

set (VERSION_FILE_SUFFIX "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_REVISION}")

if (NOT "${VERSION_TAG}" STREQUAL "")
	set (VERSION_TAG_SUFFIX " ${VERSION_TAG}")
	set (VERSION_FILE_SUFFIX "${VERSION_FILE_SUFFIX}-${VERSION_TAG}")
else ()
	set (VERSION_TAG_SUFFIX)
endif ()

set (VERSION_COMPANY   "Tibbo Technology Inc")
set (VERSION_YEARS     "2007-2015")
